# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  - hhvm

before_install:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source

script:
  - phpunit --configuration ./phpunit.xml --coverage-text

notifications:
  email: false

# reduce commit history of git checkout
git:
  depth: 1